import { addDays, format, subDays } from "date-fns";
import type { Item } from "./types";

const d = (offset: number) => format(addDays(new Date(), offset), "yyyy-MM-dd");
const past = (offset: number) => format(subDays(new Date(), offset), "yyyy-MM-dd");

function make(partial: Partial<Item>, i: number): Item {
  return {
    id: `demo-${i}`,
    kind: "event",
    status: "saved",
    title: "Untitled",
    summary: null,
    venue: null,
    area: null,
    address: null,
    category: null,
    price: null,
    url: null,
    booking_url: null,
    image_url: null,
    starts_on: null,
    ends_on: null,
    planned_for: null,
    lat: null,
    lng: null,
    color: null,
    notes: null,
    source: "manual",
    raw_input: null,
    added_by_email: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    ...partial,
  };
}

// Visible only with ?demo in the URL — never written to the database.
const seeds: Partial<Item>[] = [
  {
    title: "Yoshitomo Nara",
    venue: "Hayward Gallery",
    area: "South Bank",
    category: "exhibition",
    price: "£18",
    starts_on: past(40),
    ends_on: d(10),
    lat: 51.5056,
    lng: -0.1166,
    color: "#e0906f",
  },
  {
    title: "Beryl Cook / Tom of Finland",
    venue: "Studio Voltaire",
    area: "Clapham",
    category: "exhibition",
    price: "Free",
    starts_on: past(80),
    ends_on: d(3),
    lat: 51.4655,
    lng: -0.138,
  },
  {
    title: "Marina Abramović",
    venue: "Royal Academy",
    area: "Mayfair",
    category: "exhibition",
    price: "£25",
    starts_on: d(51),
    ends_on: d(160),
  },
  {
    title: "Frieze Sculpture",
    venue: "Regent's Park",
    area: "Regent's Park",
    category: "outdoors",
    price: "Free",
    starts_on: d(5),
    ends_on: d(30),
    status: "saved",
  },
  {
    title: "Café Deco",
    kind: "place",
    venue: "Café Deco",
    area: "Bloomsbury",
    category: "cafe",
    lat: 51.5205,
    lng: -0.125,
    color: "#4a7043",
  },
  {
    title: "Marcella",
    kind: "place",
    venue: "Marcella",
    area: "South Bank",
    category: "food",
    lat: 51.503,
    lng: -0.112,
  },
  {
    title: "The Understudy",
    kind: "place",
    venue: "The Understudy",
    area: "South Bank",
    category: "drink",
    lat: 51.5079,
    lng: -0.1082,
  },
  {
    title: "Emily Kam Kngwarray",
    venue: "Tate Modern",
    area: "South Bank",
    category: "exhibition",
    price: "£20",
    starts_on: past(30),
    ends_on: d(8),
    lat: 51.5076,
    lng: -0.0994,
    color: "#b0483a",
  },
  {
    title: "Dirty Looks",
    venue: "Barbican",
    area: "Barbican",
    category: "exhibition",
    price: "£16",
    starts_on: past(10),
    ends_on: d(14),
    lat: 51.5202,
    lng: -0.0937,
    color: "#3d5a80",
  },
  {
    title: "London Design Festival",
    area: "Citywide",
    category: "festival",
    price: "Free",
    starts_on: d(1),
    ends_on: d(9),
  },
  {
    title: "Brawn",
    kind: "place",
    venue: "Brawn",
    area: "Columbia Road",
    category: "food",
  },
  {
    title: "Columbia Road Flower Market",
    area: "Bethnal Green",
    category: "market",
    price: "Free",
    starts_on: d(3),
    ends_on: d(3),
    lat: 51.529,
    lng: -0.0692,
  },
  {
    title: "Ed Atkins",
    venue: "Tate Britain",
    area: "Pimlico",
    category: "exhibition",
    starts_on: past(120),
    ends_on: past(30),
    status: "done",
    updated_at: subDays(new Date(), 34).toISOString(),
    color: "#6b7d8f",
  },
  {
    title: "God's Own Junkyard",
    kind: "place",
    venue: "God's Own Junkyard",
    area: "Walthamstow",
    category: "outdoors",
    status: "done",
    updated_at: subDays(new Date(), 4).toISOString(),
  },
  {
    title: "Cartier",
    venue: "V&A",
    area: "South Kensington",
    category: "exhibition",
    price: "£27",
    starts_on: past(200),
    ends_on: past(15),
  },
];

export const DEMO_ITEMS: Item[] = seeds.map(make);
